@user1 = User.create(full_name: "Thomas Shapiro", email: "gramventure2016@gmail.com", instagram_handle: "lighthouselabsmtl", bio: "Cause maybe, you're gonna be the one that saves me?", personal_website: "www.lighthouselabs.com", cover_image_url: "www.facebook.com", instagram_id: "3410153537")
@user2 = User.create(full_name: "Ahmed Benchekroun", email: "gramventure2017@gmail.com", instagram_handle: "lighthouselabsmtl1", bio: "Once upon a time I was falling in love, now I'm only falling apart.", personal_website: "www.lighthouselabs.com", cover_image_url: "www.facebook.com", instagram_id: "3414201910")
@user3 = User.create(full_name: "Dominic Tremblay", email: "gramventure2018@gmail.com", instagram_handle: "lighthouselabsmtl2", bio: "Did you ever know that you're my hero?", personal_website: "www.lighthouselabs.com", cover_image_url: "www.facebook.com", instagram_id: "3414263217")
@user4 = User.create(full_name: "Adriana Molano", email: "gramventure19@gmail.com", instagram_handle: "lighthouselabsmtl3", bio: "I'm so bright, you already know.", personal_website: "www.lighthouselabs.com", cover_image_url: "www.facebook.com", instagram_id: "3414326714")
@user5 = User.create(full_name: "Horatiu Halmaghi", email: "gramventure2020@gmail.com", instagram_handle: "lighthouselabsmtl4", bio: "Is this the real life? Is this just fantasy?", personal_website: "www.lighthouselabs.com", cover_image_url: "www.facebook.com", instagram_id: "3414258426")
@user6 = User.create(full_name: "Ashley Cogan", email: "gramventure2021@gmail.com", instagram_handle: "lighthouselabsmtl5", bio: "There's always gonna be another mountain, I'm always gonna wanna make it move.", personal_website: "www.lighthouselabs.com", cover_image_url: "www.facebook.com", instagram_id: "3417709037")
@user7 = User.create(full_name: "Serkan Yorlumaz", email: "gramventure2022@gmail.com", instagram_handle: "lighthouselabsmtl6", bio: "I could stay awake just to hear you breathing.", personal_website: "www.lighthouselabs.com", cover_image_url: "www.facebook.com", instagram_id: "3417709268")
@user8 = User.create(full_name: "Alexandre Renaud", email: "gramventure2023@gmail.com", instagram_handle: "lighthouselabsmtl7", bio: "Drove my chevy to the levy but the levy was dry.", personal_website: "www.lighthouselabs.com", cover_image_url: "www.facebook.com", instagram_id: "3417577403")
@user9 = User.create(full_name: "Pedro Domingua", email: "gramventure2024@gmail.com", instagram_handle: "lighthouselabsmtl8", bio: "Mexican traveler who loves to take photos.", personal_website: "www.lighthouselabs.com", cover_image_url: "www.facebook.com")
@user10 = User.create(full_name: "Milo Enestez", email: "gramventure2025@gmail.com", instagram_handle: "lighthouselabsmtl9", bio: "Brazilian traveler who loves to take photos.", personal_website: "www.lighthouselabs.com", cover_image_url: "www.facebook.com")
@gramventure1 = Gramventure.create(cover_image_url: "https://res.cloudinary.com/twenty20/image/private/t_watermark-criss-cross-10/v1462827578000/photosp/fa08a620-8b99-4e37-b4ef-0939078040c7.jpg", name: "Gardening", brief: "What We're Looking For: We are looking for photos of gardening during the Summer. Whether it's a photo of someone watering flowers in their backyard, a father and son planting a tree at the park, or a woman checking if her tomatoes are ready to be picked- submit a photo of gardening.", submission_end: "2016-06-18-10:00", voting_end: "2016-06-22-10:00", prize: "$50", hashtag: "gramventuregardening", winning_submission_id: "")
@gramventure2 = Gramventure.create(cover_image_url: "https://res.cloudinary.com/twenty20/image/private/t_watermark-criss-cross-10/v1445637239000/photosp/348d076e-a228-4489-819a-4be4c25ea854.jpg", name: "Neon Lights", brief: "What We're Looking For: We are looking for fun, colorful photos of neon lights. Whether it's a photo of a lit sign in the window of a business, bright lights inside a dance club, or an outdoor restaurant lined in colorful lights- submit a creative photo of neon lights.", submission_end: "2016-06-20-10:00", voting_end: "2016-06-24-10:00", prize: "$40", hashtag: "gramventureneon", winning_submission_id: "")
@gramventure3 = Gramventure.create(cover_image_url: "https://res.cloudinary.com/twenty20/image/private/t_watermark-criss-cross-10/v1464653824000/photosp/519379d2-cdd1-4c5d-a1b9-f31242fcdf4f.jpg", name: "Road Trip", brief: "What We're Looking For: We are looking for photos of road trips. Whether it's a photo of your mother sitting in the passenger seat with a map, your boyfriend driving a RV, your sister sleeping in the backseat, or your friends dancing in the car on the highway- submit a photo of people on a road trip.", submission_end: "2016-06-21-10:00", voting_end: "2016-06-25-10:00", prize: "$45", hashtag: "gramventureroadtrip", winning_submission_id: "")
@gramventure4 = Gramventure.create(cover_image_url: "https://res.cloudinary.com/twenty20/image/private/t_watermark-criss-cross-10/v1449779636000/photosp/9bbda596-4b7c-48d2-856e-1a18d59db0b6.jpg", name: "Walking Dogs", brief: "What We're Looking For: We are looking for photos of people walking their dog. Whether it's a business woman taking her dog out during a lunch break, a teenage boy strolling the neighborhood with his dog after school, or a dog walker with a group of dogs at the park- submit a photo of someone walking their dog.", submission_end: "2016-06-20-10:00", voting_end: "2016-06-24-10:00", prize: "$40", hashtag: "gramventurewalkingdogs", winning_submission_id: "")
@gramventure5 = Gramventure.create(cover_image_url: "https://res.cloudinary.com/twenty20/image/private/t_watermark-criss-cross-10/v1464900714000/photosp/479bba5c-89d9-4e05-8188-b10878619627.jpg", name: "Apartment Living", brief: "What We're Looking For: We are looking for photos that capture the home life of middle-income apartment dwellers. We would like to see people of all ages doing everyday things in their apartment or common areas; clean, uncluttered spaces are ideal. Whether it's a photo of someone grilling on the balcony, splashing in the apartment pool, or relaxing on the couch while watching the kids play with the family pet- submit a lifestyle photo of apartment dwellers.", submission_end: "2016-06-11-10:00", voting_end: "2016-06-24-10:00", prize: "$40", hashtag: "gramventureapartmentliving", winning_submission_id: "")
@gramventure6 = Gramventure.create(cover_image_url: "https://res.cloudinary.com/twenty20/image/private/t_standard-fit/v1462150602/photosp/3be98037-c99c-433a-a31e-84eb8b3a3ee5.jpg", name: "Landscapes", brief: "What We're Looking For: What is your most beautiful landscape photo? Whether it's a photo of a breathtaking ocean view, a blissful meadow amidst a mountain range, or a forest glowing at sunrise- submit a bright photo of a beautiful landscape.", submission_end: "2016-06-01-10:00", voting_end: "2016-06-02-10:00", prize: "$40", hashtag: "gramventurelandscapes", winning_submission_id: "")
@submission1 = Submission.create(image_id: "1", gramventure_id: "2")
@submission2 = Submission.create(image_id: "2", gramventure_id: "2")
@submission3 = Submission.create(image_id: "3", gramventure_id: "2")
@submission4 = Submission.create(image_id: "4", gramventure_id: "2")
@submission5 = Submission.create(image_id: "5", gramventure_id: "2")
@submission6 = Submission.create(image_id: "6", gramventure_id: "4") 
@submission7 = Submission.create(image_id: "7", gramventure_id: "4")
@submission8 = Submission.create(image_id: "8", gramventure_id: "4")
@submission9 = Submission.create(image_id: "9", gramventure_id: "4")
@submission10 = Submission.create(image_id: "10", gramventure_id: "3")
@submission11 = Submission.create(image_id: "11", gramventure_id: "3")
@submission12 = Submission.create(image_id: "12", gramventure_id: "3")
@submission13 = Submission.create(image_id: "13", gramventure_id: "3")
@submission14 = Submission.create(image_id: "14", gramventure_id: "3")
@submission15 = Submission.create(image_id: "15", gramventure_id: "1")
@submission16 = Submission.create(image_id: "16", gramventure_id: "1")
@submission17 = Submission.create(image_id: "17", gramventure_id: "1")
@submission18 = Submission.create(image_id: "18", gramventure_id: "1")
@submission19 = Submission.create(image_id: "19", gramventure_id: "1")
@submission20 = Submission.create(image_id: "20", gramventure_id: "1")
@submission21 = Submission.create(image_id: "21", gramventure_id: "3") 
@submission22 = Submission.create(image_id: "22", gramventure_id: "3") 
@submission23 = Submission.create(image_id: "23", gramventure_id: "4") 
@submission24 = Submission.create(image_id: "24", gramventure_id: "4") 
@submission25 = Submission.create(image_id: "25", gramventure_id: "2") 
@submission26 = Submission.create(image_id: "26", gramventure_id: "2") 
@submission27 = Submission.create(image_id: "27", gramventure_id: "1") 
@submission28 = Submission.create(image_id: "28", gramventure_id: "1") 
@submission29 = Submission.create(image_id: "29", gramventure_id: "3") 
@submission30 = Submission.create(image_id: "30", gramventure_id: "3") 
@submission31 = Submission.create(image_id: "31", gramventure_id: "4")
@submission32 = Submission.create(image_id: "32", gramventure_id: "4")
@submission33 = Submission.create(image_id: "33", gramventure_id: "2")
@submission34 = Submission.create(image_id: "34", gramventure_id: "2")
@submission35 = Submission.create(image_id: "35", gramventure_id: "1")
@submission36 = Submission.create(image_id: "36", gramventure_id: "1")
@submission37 = Submission.create(image_id: "37", gramventure_id: "6")
@submission38 = Submission.create(image_id: "38", gramventure_id: "6")
@submission39 = Submission.create(image_id: "39", gramventure_id: "5")
@submission40 = Submission.create(image_id: "40", gramventure_id: "5") 
@submission41 = Submission.create(image_id: "41", gramventure_id: "4")
@submission42 = Submission.create(image_id: "42", gramventure_id: "4")
@submission43 = Submission.create(image_id: "43", gramventure_id: "2")
@submission44 = Submission.create(image_id: "44", gramventure_id: "2")
@submission45 = Submission.create(image_id: "45", gramventure_id: "2")
@submission46 = Submission.create(image_id: "46", gramventure_id: "3")
@submission47 = Submission.create(image_id: "47", gramventure_id: "3")
@submission48 = Submission.create(image_id: "48", gramventure_id: "1")
@submission49 = Submission.create(image_id: "49", gramventure_id: "1")
@submission50 = Submission.create(image_id: "50", gramventure_id: "1")
@submission51 = Submission.create(image_id: "51", gramventure_id: "5")
@submission52 = Submission.create(image_id: "52", gramventure_id: "5")
@submission53 = Submission.create(image_id: "53", gramventure_id: "6")
@submission54 = Submission.create(image_id: "54", gramventure_id: "6")
@submission55 = Submission.create(image_id: "55", gramventure_id: "1")
@submission56 = Submission.create(image_id: "56", gramventure_id: "1")
@submission57 = Submission.create(image_id: "57", gramventure_id: "6")
@submission58 = Submission.create(image_id: "58", gramventure_id: "6")
@submission59 = Submission.create(image_id: "59", gramventure_id: "5")
@submission60 = Submission.create(image_id: "60", gramventure_id: "5")
@submission61 = Submission.create(image_id: "61", gramventure_id: "3")
@submission62 = Submission.create(image_id: "62", gramventure_id: "3")
@submission63 = Submission.create(image_id: "63", gramventure_id: "2")
@submission64 = Submission.create(image_id: "64", gramventure_id: "2")
@submission65 = Submission.create(image_id: "65", gramventure_id: "4")
@submission66 = Submission.create(image_id: "66", gramventure_id: "4")
@submission67 = Submission.create(image_id: "67", gramventure_id: "3")
@submission68 = Submission.create(image_id: "68", gramventure_id: "3")
@submission69 = Submission.create(image_id: "69", gramventure_id: "5")
@submission70 = Submission.create(image_id: "70", gramventure_id: "5")
@submission71 = Submission.create(image_id: "71", gramventure_id: "6")
@submission72 = Submission.create(image_id: "72", gramventure_id: "6")
@submission73 = Submission.create(image_id: "73", gramventure_id: "1")
@submission74 = Submission.create(image_id: "74", gramventure_id: "4")
@submission75 = Submission.create(image_id: "75", gramventure_id: "4")
@submission76 = Submission.create(image_id: "76", gramventure_id: "2")
@submission77 = Submission.create(image_id: "77", gramventure_id: "2")
@submission78 = Submission.create(image_id: "78", gramventure_id: "1")
@submission79 = Submission.create(image_id: "79", gramventure_id: "3")
@submission80 = Submission.create(image_id: "80", gramventure_id: "3")
@submission81 = Submission.create(image_id: "81", gramventure_id: "5")
@submission82 = Submission.create(image_id: "82", gramventure_id: "5")
@submission83 = Submission.create(image_id: "83", gramventure_id: "6")
@submission84 = Submission.create(image_id: "84", gramventure_id: "6")
@submission85 = Submission.create(image_id: "85", gramventure_id: "6")
@submission86 = Submission.create(image_id: "86", gramventure_id: "6")
@submission87 = Submission.create(image_id: "87", gramventure_id: "1")
@submission88 = Submission.create(image_id: "88", gramventure_id: "1")
@submission89 = Submission.create(image_id: "89", gramventure_id: "4")
@submission90 = Submission.create(image_id: "90", gramventure_id: "2")
@vote1 = Vote.create(user_id: "1" , submission_id: "2")
@vote2 = Vote.create(user_id: "3" , submission_id: "4")
@vote3 = Vote.create(user_id: "2" , submission_id: "1")
@vote4 = Vote.create(user_id: "8" , submission_id: "3")
@vote5 = Vote.create(user_id: "1" , submission_id: "5")
@vote6 = Vote.create(user_id: "4" , submission_id: "6")
@vote7 = Vote.create(user_id: "10" , submission_id: "4")
@vote8 = Vote.create(user_id: "4" , submission_id: "5")
@vote9 = Vote.create(user_id: "7" , submission_id: "2")
@vote10 = Vote.create(user_id: "4" , submission_id: "4")
@vote11 = Vote.create(user_id: "1" , submission_id: "12")
@vote12 = Vote.create(user_id: "3" , submission_id: "14")
@vote13 = Vote.create(user_id: "2" , submission_id: "11")
@vote14 = Vote.create(user_id: "8" , submission_id: "13")
@vote15 = Vote.create(user_id: "1" , submission_id: "15")
@vote16 = Vote.create(user_id: "4" , submission_id: "16")
@vote17 = Vote.create(user_id: "10" , submission_id: "14")
@vote18 = Vote.create(user_id: "4" , submission_id: "15")
@vote19 = Vote.create(user_id: "7" , submission_id: "12")
@vote20 = Vote.create(user_id: "4" , submission_id: "14")
@image1 = Image.create(url: "https://www.instagram.com/p/BGmsCfsN0tl/?taken-by=lighthouselabsmtl&hl=en", user_id: "1")
@image2 = Image.create(url: "https://www.instagram.com/p/BGmsFlwt0tv/?taken-by=lighthouselabsmtl&hl=en", user_id: "1")
@image3 = Image.create(url: "https://www.instagram.com/p/BGmsIhbN0t9/?taken-by=lighthouselabsmtl&hl=en", user_id: "1")
@image4 = Image.create(url: "https://www.instagram.com/p/BGmsLT2t0uF/?taken-by=lighthouselabsmtl&hl=en", user_id: "1")
@image5 = Image.create(url: "https://www.instagram.com/p/BGmsNKvN0uH/?taken-by=lighthouselabsmtl&hl=en", user_id: "1")
@image6 = Image.create(url: "https://www.instagram.com/p/BGmsg6pt0u8/?taken-by=lighthouselabsmtl&hl=en", user_id: "1")
@image7 = Image.create(url: "https://www.instagram.com/p/BGms3kht0gI/?taken-by=lighthouselabsmtl&hl=en", user_id: "1")
@image8 = Image.create(url: "https://www.instagram.com/p/BGms5L-N0gM/?taken-by=lighthouselabsmtl&hl=en", user_id: "1")
@image9 = Image.create(url: "https://www.instagram.com/p/BGms7gDN0gT/?taken-by=lighthouselabsmtl&hl=en", user_id: "1")
@image10 = Image.create(url: "https://www.instagram.com/p/BGms-N6t0ge/?taken-by=lighthouselabsmtl&hl=en", user_id: "1")
@image11 = Image.create(url: "https://www.instagram.com/p/BGmtAMlN0gi/?taken-by=lighthouselabsmtl&hl=en", user_id: "1")
@image12 = Image.create(url: "https://www.instagram.com/p/BGmtB_1N0gm/?taken-by=lighthouselabsmtl&hl=en", user_id: "1")
@image13 = Image.create(url: "https://www.instagram.com/p/BGmtI44N0g6/?taken-by=lighthouselabsmtl&hl=en", user_id: "1")
@image14 = Image.create(url: "https://www.instagram.com/p/BGmtLoqN0hH/?taken-by=lighthouselabsmtl&hl=en", user_id: "1")
@image15 = Image.create(url: "https://www.instagram.com/p/BGmtO1AN0hP/?taken-by=lighthouselabsmtl&hl=en", user_id: "1")
@image16 = Image.create(url: "https://www.instagram.com/p/BGmtRCdN0hZ/?taken-by=lighthouselabsmtl&hl=en", user_id: "1")
@image17 = Image.create(url: "https://www.instagram.com/p/BGmtS4hN0hg/?taken-by=lighthouselabsmtl&hl=en", user_id: "1")
@image18 = Image.create(url: "https://www.instagram.com/p/BGmtUtrt0hm/?taken-by=lighthouselabsmtl&hl=en", user_id: "1")
@image19 = Image.create(url: "https://www.instagram.com/p/BGmtWlUN0hu/?taken-by=lighthouselabsmtl&hl=en", user_id: "1")
@image20 = Image.create(url: "https://www.instagram.com/p/BGmtZjKN0h9/?taken-by=lighthouselabsmtl&hl=en", user_id: "1")
@image21 = Image.create(url: "https://www.instagram.com/p/BGqWSz0ndzl/?taken-by=lighthouselabsmtl1", user_id: "2")
@image22 = Image.create(url: "https://www.instagram.com/p/BGqWU6FHdzp/?taken-by=lighthouselabsmtl1", user_id: "2")
@image23 = Image.create(url: "https://www.instagram.com/p/BGqWXRJHdzw/?taken-by=lighthouselabsmtl1", user_id: "2")
@image24 = Image.create(url: "https://www.instagram.com/p/BGqWXRJHdzw/?taken-by=lighthouselabsmtl1", user_id: "2")
@image25 = Image.create(url: "https://www.instagram.com/p/BGqWb9indz4/?taken-by=lighthouselabsmtl1", user_id: "2")
@image26 = Image.create(url: "https://www.instagram.com/p/BGqWdneHdz7/?taken-by=lighthouselabsmtl1", user_id: "2")
@image27 = Image.create(url: "https://www.instagram.com/p/BGqWgY0Hd0B/?taken-by=lighthouselabsmtl1", user_id: "2")
@image28 = Image.create(url: "https://www.instagram.com/p/BGqWkJKHd0K/?taken-by=lighthouselabsmtl1", user_id: "2")
@image29 = Image.create(url: "https://www.instagram.com/p/BGqW45VMkpA/?taken-by=lighthouselabsmtl2", user_id: "3")
@image30 = Image.create(url: "https://www.instagram.com/p/BGqW8-SMkpJ/?taken-by=lighthouselabsmtl2", user_id: "3")
@image31 = Image.create(url: "https://www.instagram.com/p/BGqXARLskpQ/?taken-by=lighthouselabsmtl2", user_id: "3")
@image32 = Image.create(url: "https://www.instagram.com/p/BGqXhCeskp_/?taken-by=lighthouselabsmtl2", user_id: "3")
@image33 = Image.create(url: "https://www.instagram.com/p/BGt8eFoMkqX/?taken-by=lighthouselabsmtl2", user_id: "3")
@image34 = Image.create(url: "https://www.instagram.com/p/BGt8h6tskqg/?taken-by=lighthouselabsmtl2", user_id: "3")
@image35 = Image.create(url: "https://www.instagram.com/p/BGt8mA_Mkqm/?taken-by=lighthouselabsmtl2", user_id: "3")
@image36 = Image.create(url: "https://www.instagram.com/p/BGt8psfMkqz/?taken-by=lighthouselabsmtl2", user_id: "3")
@image37 = Image.create(url: "https://www.instagram.com/p/BGuOlkvMkra/?taken-by=lighthouselabsmtl2", user_id: "3")
@image38 = Image.create(url: "https://www.instagram.com/p/BGuOqmaskrn/?taken-by=lighthouselabsmtl2", user_id: "3")
@image39 = Image.create(url: "https://www.instagram.com/p/BGuO0sLMksL/?taken-by=lighthouselabsmtl2", user_id: "3")
@image40 = Image.create(url: "https://www.instagram.com/p/BGuO3tGMksW/?taken-by=lighthouselabsmtl2", user_id: "3")
@image41 = Image.create(url: "https://www.instagram.com/p/BGt81yNms-H/?taken-by=lighthouselabsmtl3", user_id: "4")
@image42 = Image.create(url: "https://www.instagram.com/p/BGt84pfms-R/?taken-by=lighthouselabsmtl3", user_id: "4")
@image43 = Image.create(url: "https://www.instagram.com/p/BGt86-9Gs-T/?taken-by=lighthouselabsmtl3", user_id: "4")
@image44 = Image.create(url: "https://www.instagram.com/p/BGt89Edms-X/?taken-by=lighthouselabsmtl3", user_id: "4")
@image45 = Image.create(url: "https://www.instagram.com/p/BGt8-tTGs-g/?taken-by=lighthouselabsmtl3", user_id: "4")
@image46 = Image.create(url: "https://www.instagram.com/p/BGt9B2dGs-q/?taken-by=lighthouselabsmtl3", user_id: "4")
@image47 = Image.create(url: "https://www.instagram.com/p/BGt9DVYms-s/?taken-by=lighthouselabsmtl3", user_id: "4")
@image48 = Image.create(url: "https://www.instagram.com/p/BGt9Gfxms-3/?taken-by=lighthouselabsmtl3", user_id: "4")
@image49 = Image.create(url: "https://www.instagram.com/p/BGt9J9sGs_C/?taken-by=lighthouselabsmtl3", user_id: "4")
@image50 = Image.create(url: "https://www.instagram.com/p/BGt9alEms_z/?taken-by=lighthouselabsmtl3", user_id: "4")
@image51 = Image.create(url: "https://www.instagram.com/p/BGuQKr_Gs-F/?taken-by=lighthouselabsmtl3", user_id: "4")
@image52 = Image.create(url: "https://www.instagram.com/p/BGuQPMMGs-M/?taken-by=lighthouselabsmtl3", user_id: "4")
@image53 = Image.create(url: "https://www.instagram.com/p/BGuQSjYms-U/?taken-by=lighthouselabsmtl3", user_id: "4")
@image54 = Image.create(url: "https://www.instagram.com/p/BGuQVUBms-d/?taken-by=lighthouselabsmtl3", user_id: "4")
@image55 = Image.create(url: "https://www.instagram.com/p/BGuQqGANYy3/?taken-by=lighthouselabsmtl4", user_id: "5")
@image56 = Image.create(url: "https://www.instagram.com/p/BGuQtGcNYzB/?taken-by=lighthouselabsmtl4", user_id: "5")
@image57 = Image.create(url: "https://www.instagram.com/p/BGuQw6NtYzQ/?taken-by=lighthouselabsmtl4", user_id: "5")
@image58 = Image.create(url: "https://www.instagram.com/p/BGuQzPOtYzd/?taken-by=lighthouselabsmtl4", user_id: "5")
@image59 = Image.create(url: "https://www.instagram.com/p/BGuQ21yNYzq/?taken-by=lighthouselabsmtl4", user_id: "5")
@image60 = Image.create(url: "https://www.instagram.com/p/BGuQ-W8tYz9/?taken-by=lighthouselabsmtl4", user_id: "5")
@image61 = Image.create(url: "https://www.instagram.com/p/BGuRCYstY0R/?taken-by=lighthouselabsmtl4", user_id: "5")
@image62 = Image.create(url: "https://www.instagram.com/p/BGuREiEtY0c/?taken-by=lighthouselabsmtl4", user_id: "5")
@image63 = Image.create(url: "https://www.instagram.com/p/BGuRPAINY07/?taken-by=lighthouselabsmtl4", user_id: "5")
@image64 = Image.create(url: "https://www.instagram.com/p/BGuRSUjtY1K/?taken-by=lighthouselabsmtl4", user_id: "5")
@image65 = Image.create(url: "https://www.instagram.com/p/BGuRYO-NY1Y/?taken-by=lighthouselabsmtl4", user_id: "5")
@image66 = Image.create(url: "https://www.instagram.com/p/BGuRedOtY1s/?taken-by=lighthouselabsmtl4", user_id: "5")
@image67 = Image.create(url: "https://www.instagram.com/p/BGuSnY9vxnl/?taken-by=lighthouselabsmtl5", user_id: "6")
@image68 = Image.create(url: "https://www.instagram.com/p/BGuSrlCvxnx/?taken-by=lighthouselabsmtl5", user_id: "6")
@image69 = Image.create(url: "https://www.instagram.com/p/BGuSzPvvxoD/?taken-by=lighthouselabsmtl5", user_id: "6")
@image70 = Image.create(url: "https://www.instagram.com/p/BGuS2hnvxoM/?taken-by=lighthouselabsmtl5", user_id: "6")
@image71 = Image.create(url: "https://www.instagram.com/p/BGuS9GPvxoc/?taken-by=lighthouselabsmtl5", user_id: "6")
@image72 = Image.create(url: "https://www.instagram.com/p/BGuTApBvxol/?taken-by=lighthouselabsmtl5", user_id: "6")
@image73 = Image.create(url: "https://www.instagram.com/p/BGuTFgIPxo2/?taken-by=lighthouselabsmtl5", user_id: "6")
@image74 = Image.create(url: "https://www.instagram.com/p/BGuTIRTPxpC/?taken-by=lighthouselabsmtl5", user_id: "6")
@image75 = Image.create(url: "https://www.instagram.com/p/BGuTLfyPxpK/?taken-by=lighthouselabsmtl5", user_id: "6")
@image76 = Image.create(url: "https://www.instagram.com/p/BGuTOGbvxpT/?taken-by=lighthouselabsmtl5", user_id: "6")
@image77 = Image.create(url: "https://www.instagram.com/p/BGuTQp8vxpa/?taken-by=lighthouselabsmtl5", user_id: "6")
@image78 = Image.create(url: "https://www.instagram.com/p/BGuTSwrPxph/?taken-by=lighthouselabsmtl5", user_id: "6")
@image79 = Image.create(url: "https://www.instagram.com/p/BGuVmcCwrfm/?taken-by=lighthouselabsmtl6", user_id: "7")
@image80 = Image.create(url: "https://www.instagram.com/p/BGuVqpSwrfu/?taken-by=lighthouselabsmtl6", user_id: "7")
@image81 = Image.create(url: "https://www.instagram.com/p/BGuVtTWQrf4/?taken-by=lighthouselabsmtl6", user_id: "7")
@image82 = Image.create(url: "https://www.instagram.com/p/BGuVxjWQrQC/?taken-by=lighthouselabsmtl6", user_id: "7")
@image83 = Image.create(url: "https://www.instagram.com/p/BGuV1wawrQN/?taken-by=lighthouselabsmtl6", user_id: "7")
@image84 = Image.create(url: "https://www.instagram.com/p/BGuV5bcQrQU/?taken-by=lighthouselabsmtl6", user_id: "7")
@image85 = Image.create(url: "https://www.instagram.com/p/BGuV7IRQrQa/?taken-by=lighthouselabsmtl6", user_id: "7")
@image86 = Image.create(url: "https://www.instagram.com/p/BGuV9adQrQk/?taken-by=lighthouselabsmtl6", user_id: "7")
@image87 = Image.create(url: "https://www.instagram.com/p/BGuV_4ZQrQv/?taken-by=lighthouselabsmtl6", user_id: "7")
@image88 = Image.create(url: "https://www.instagram.com/p/BGuWCMCwrQ4/?taken-by=lighthouselabsmtl6", user_id: "7")
@image89 = Image.create(url: "https://www.instagram.com/p/BGuWElGwrRA/?taken-by=lighthouselabsmtl6", user_id: "7")
@image90 = Image.create(url: "https://www.instagram.com/p/BGuWHbAQrRI/?taken-by=lighthouselabsmtl6", user_id: "7")
@image91 = Image.create(url: "", user_id: "")
@usergramventure1 = Usergramventure.create(user_id: "1", gramventure_id: "1")
@usergramventure2 = Usergramventure.create(user_id: "2", gramventure_id: "1")
@usergramventure3 = Usergramventure.create(user_id: "3", gramventure_id: "2")
@usergramventure4 = Usergramventure.create(user_id: "4", gramventure_id: "2")
@usergramventure5 = Usergramventure.create(user_id: "5", gramventure_id: "3")
@usergramventure6 = Usergramventure.create(user_id: "6", gramventure_id: "3")
@usergramventure7 = Usergramventure.create(user_id: "7", gramventure_id: "4")
@usergramventure8 = Usergramventure.create(user_id: "8", gramventure_id: "4")
@usergramventure9 = Usergramventure.create(user_id: "9", gramventure_id: "4")
@usergramventure10 = Usergramventure.create(user_id: "10", gramventure_id: "2")